# Generated by Django 3.1.2 on 2021-01-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='telefono',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='telefono2',
            field=models.PositiveIntegerField(blank=True, default='809-221-3041'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='telefono3',
            field=models.PositiveIntegerField(blank=True, default='809-968-9333'),
        ),
    ]
