# Generated by Django 3.1.2 on 2021-01-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_auto_20210120_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='telefono2',
            field=models.PositiveIntegerField(default='8092213041'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='telefono3',
            field=models.PositiveIntegerField(default='8099689333'),
        ),
    ]
