# Generated by Django 3.1.2 on 2021-02-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_auto_20210203_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='testfield',
            field=models.PositiveIntegerField(default='8099689333'),
        ),
    ]
