# Generated by Django 3.1.2 on 2021-02-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agent_testfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='testfield',
        ),
    ]
