# Generated by Django 3.1.2 on 2021-02-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_remove_agent_testfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='estado',
            field=models.BooleanField(choices=[(1, 'Activada'), (0, 'Desactivada')], default=1, max_length=1),
        ),
    ]
