# Generated by Django 3.1.2 on 2021-02-04 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_agent_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='estado',
        ),
    ]
