# Generated by Django 3.1.2 on 2021-02-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_remove_agent_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='zona_operacion',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
