# Generated by Django 3.1.2 on 2021-01-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=11)),
                ('zona', models.CharField(max_length=100)),
                ('prox', models.CharField(max_length=200)),
                ('habs', models.PositiveSmallIntegerField()),
                ('banos', models.PositiveSmallIntegerField()),
                ('mts', models.FloatField()),
                ('parqueos', models.PositiveSmallIntegerField()),
                ('piso', models.PositiveSmallIntegerField()),
                ('sala', models.BooleanField()),
                ('comedor', models.BooleanField()),
                ('balcon', models.BooleanField()),
                ('terraza', models.BooleanField()),
                ('desc', models.TextField()),
                ('ascensor', models.BooleanField()),
                ('planta_full', models.BooleanField()),
                ('planta_areas', models.BooleanField()),
                ('gas_comun', models.BooleanField()),
                ('gas_comun_med', models.BooleanField()),
                ('seguridad24', models.BooleanField()),
                ('piscina', models.BooleanField()),
                ('gym', models.BooleanField()),
                ('area_comun', models.BooleanField()),
                ('salon_actividades', models.BooleanField()),
                ('area_inf', models.BooleanField()),
                ('sauna', models.BooleanField()),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('image3', models.ImageField(upload_to='')),
                ('image4', models.ImageField(upload_to='')),
                ('image5', models.ImageField(upload_to='')),
                ('image6', models.ImageField(upload_to='')),
                ('image7', models.ImageField(upload_to='')),
                ('image8', models.ImageField(upload_to='')),
                ('image9', models.ImageField(upload_to='')),
                ('image10', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
