# Generated by Django 3.1.2 on 2021-01-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inmueble',
            options={'ordering': ['-created'], 'verbose_name': 'Inmueble', 'verbose_name_plural': 'Inmuebles'},
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='area_comun',
            field=models.BooleanField(verbose_name='Area comun'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='area_inf',
            field=models.BooleanField(verbose_name='Area infantil'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='banos',
            field=models.PositiveSmallIntegerField(verbose_name='Baños'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='desc',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='gas_comun',
            field=models.BooleanField(verbose_name='Gas comun'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='gas_comun_med',
            field=models.BooleanField(verbose_name='Gas comun con medidor'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='habs',
            field=models.PositiveSmallIntegerField(verbose_name='Habitaciones'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='image1',
            field=models.ImageField(blank=True, upload_to='Inmuebles', verbose_name='Imagen 1'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='image10',
            field=models.ImageField(blank=True, upload_to='Inmuebles', verbose_name='Imagen 10'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='image2',
            field=models.ImageField(blank=True, upload_to='Inmuebles', verbose_name='Imagen 2'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='image3',
            field=models.ImageField(blank=True, upload_to='Inmuebles', verbose_name='Imagen 3'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='image4',
            field=models.ImageField(blank=True, upload_to='Inmuebles', verbose_name='Imagen 4'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='image5',
            field=models.ImageField(blank=True, upload_to='Inmuebles', verbose_name='Imagen 5'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='image6',
            field=models.ImageField(blank=True, upload_to='Inmuebles', verbose_name='Imagen 6'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='image7',
            field=models.ImageField(blank=True, upload_to='Inmuebles', verbose_name='Imagen 7'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='image8',
            field=models.ImageField(blank=True, upload_to='Inmuebles', verbose_name='Imagen 8'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='image9',
            field=models.ImageField(blank=True, upload_to='Inmuebles', verbose_name='Imagen 9'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='mts',
            field=models.FloatField(verbose_name='Metraje'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='planta_areas',
            field=models.BooleanField(verbose_name='Planta areas comunes'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='planta_full',
            field=models.BooleanField(verbose_name='Planta full'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='prox',
            field=models.CharField(max_length=200, verbose_name='Proximo a'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='salon_actividades',
            field=models.BooleanField(verbose_name='Salon de actividades'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='seguridad24',
            field=models.BooleanField(verbose_name='Seguridad 24 horas'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Utilma modificacion'),
        ),
    ]
