# Generated by Django 3.1.2 on 2021-01-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210114_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='moneda',
            field=models.CharField(choices=[('P', 'Pesos'), ('D', 'Dolares')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='parqueos',
            field=models.PositiveSmallIntegerField(verbose_name='Parqueos'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='piso',
            field=models.PositiveSmallIntegerField(verbose_name='Piso'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='prox',
            field=models.CharField(max_length=200),
        ),
    ]
