# Generated by Django 3.1.2 on 2021-01-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210119_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='gas_comun',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='gas_comun_med',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='planta_areas',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='planta_full',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='gas',
            field=models.IntegerField(choices=[(0, 'Sin gas comun'), (1, 'Gas comun sin medidor'), (2, 'Gas comun con medidor')], default=0, max_length=1, verbose_name='Gas comun'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='planta',
            field=models.IntegerField(choices=[(0, 'Sin planta'), (1, 'Planta full'), (2, 'Planta solo areas comunes')], default=0, max_length=1, verbose_name='Planta electrica'),
        ),
    ]
