# Generated by Django 3.1.2 on 2021-01-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210119_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='parqueos_techados',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='prox',
            field=models.CharField(max_length=200, verbose_name='Proximo a'),
        ),
    ]
