# Generated by Django 3.1.2 on 2021-01-20 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_auto_20210120_0718'),
        ('portfolio', '0007_inmueble_tipo_inmo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='agente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='agents.agent', verbose_name='Agente'),
            preserve_default=False,
        ),
    ]
