# Generated by Django 3.1.2 on 2021-01-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_inmueble_agente'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='dest1',
            field=models.CharField(blank=True, default='Localizada en el corazon de la ciudad', max_length=200),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='dest10',
            field=models.CharField(blank=True, default='Destacado 10', max_length=200),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='dest11',
            field=models.CharField(blank=True, default='Destacado 11', max_length=200),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='dest12',
            field=models.CharField(blank=True, default='Destacado 12', max_length=200),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='dest2',
            field=models.CharField(blank=True, default='2 pisos de parqueo', max_length=200),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='dest3',
            field=models.CharField(blank=True, default='Estructura resistente a terremotos', max_length=200),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='dest4',
            field=models.CharField(blank=True, default='Extinguidores en cada piso', max_length=200),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='dest5',
            field=models.CharField(blank=True, default='Cerco electrico en las areas comunes', max_length=200),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='dest6',
            field=models.CharField(blank=True, default='Destacado 6', max_length=200),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='dest7',
            field=models.CharField(blank=True, default='Destacado 7', max_length=200),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='dest8',
            field=models.CharField(blank=True, default='Destacado 8', max_length=200),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='dest9',
            field=models.CharField(blank=True, default='Destacado 9', max_length=200),
        ),
    ]
