# Generated by Django 3.1.2 on 2021-01-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20210127_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='image_condo',
            field=models.ImageField(blank=True, upload_to='Inmuebles', verbose_name='Imagen del condominio (horizontal)'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='dest10',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='dest11',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='dest12',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='dest6',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='dest7',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='dest8',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='dest9',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
