# Generated by Django 3.1.2 on 2021-01-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20210127_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='image_condo',
            field=models.ImageField(upload_to='Inmuebles', verbose_name='Imagen del condominio (horizontal)'),
        ),
    ]
