# Generated by Django 3.1.2 on 2021-01-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20210127_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='cerc1',
            field=models.CharField(blank=True, default='A x minutos del supermercado x', max_length=200),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='cerc10',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='cerc11',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='cerc12',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='cerc2',
            field=models.CharField(blank=True, default='A x minutos del metro x', max_length=200),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='cerc3',
            field=models.CharField(blank=True, default='A x calles del mcdonald´s de la avenida x', max_length=200),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='cerc4',
            field=models.CharField(blank=True, default='A x calles de la clinica x', max_length=200),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='cerc5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='cerc6',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='cerc7',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='cerc8',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='cerc9',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
