# Generated by Django 3.1.2 on 2021-01-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20210127_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='map',
            field=models.URLField(default='sdasad'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='cerc3',
            field=models.CharField(blank=True, default="A x calles del mcdonald's de la avenida x", max_length=200),
        ),
    ]
