# Generated by Django 3.1.2 on 2021-01-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20210127_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='map',
            field=models.TextField(default='sdasad'),
        ),
    ]
