# Generated by Django 3.1.2 on 2021-01-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20210127_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='map',
            field=models.TextField(verbose_name='Link de la zona'),
        ),
    ]
