# Generated by Django 3.1.2 on 2021-02-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20210127_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='mant',
            field=models.IntegerField(blank=True, default=850, verbose_name='Cuota de mantenimiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Descripcion'),
        ),
    ]
