# Generated by Django 3.1.2 on 2021-02-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20210202_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='moneda_mant',
            field=models.CharField(choices=[('P', 'Pesos'), ('D', 'Dolares')], default='P', max_length=1, verbose_name='Cuota de mantenimiento'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='mant',
            field=models.IntegerField(verbose_name='Cuota de mantenimiento'),
        ),
    ]
