# Generated by Django 3.1.2 on 2021-02-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20210202_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='tipo_inmo',
            field=models.IntegerField(choices=[(1, 'Apartamento'), (2, 'Casa'), (3, 'Local'), (4, 'Solar'), (5, 'Edificio')], default=1, verbose_name='Tipo de inmueble'),
        ),
    ]
