# Generated by Django 3.1.2 on 2021-02-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_auto_20210202_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Precio'),
        ),
    ]
