# Generated by Django 3.1.2 on 2021-02-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_auto_20210202_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='estado',
            field=models.BooleanField(choices=[(1, 'Activada'), (0, 'Desactivada')], default=1, max_length=1),
        ),
    ]
