# Generated by Django 3.1.2 on 2021-02-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_inmueble_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Activada'), (0, 'Desactivada')], default=1, max_length=1),
        ),
    ]
